TEMPSENSORPIN = 4
BODENSENSORPIN = 18
CSV_FILENAME = "Lesedaten.csv"
SENSOR_MAXTRIES = 5
SENSOR_SLEEP_BETWEEN_TRIES_SECONDS = 2 # in seconds
MAIN_LOOP_TICK_SECONDS = 10
CAMERA_SKIP_MEASUREMENTS = 15
IMAGE_PATH = "./Images/"
